{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_two.Test_Two object at 0x0000020284E52410>\n\n    @allure.severity(allure.severity_level.BLOCKER)\n    def test_two(self):\n        self.driver.find_element(By.XPATH, \"//option[@value='volvox']\").click()\n>       assert False\nE       assert False\n\ntest_two.py:12: AssertionError"}, "start": 1691146004560, "stop": 1691146004601, "uuid": "b0ecc41e-53a9-4698-9102-f17217b6bc7e", "historyId": "12c0c162b00395656bea66ee223ab37d", "testCaseId": "12c0c162b00395656bea66ee223ab37d", "fullName": "SeleniumPyTest.test_two.Test_Two#test_two", "labels": [{"name": "severity", "value": "blocker"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "SeleniumPyTest"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test_Two"}, {"name": "host", "value": "MT-5CD119LDX7"}, {"name": "thread", "value": "28708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "SeleniumPyTest.test_two"}]}